### ISSUE TITLE
Error with OpenAL

### ISSUE THREAD

**Issue by maek** [unrealarena/unrealarena#30]
As reported by @illwieckz, on Ubuntu 15.4 the current snapshot (0.1-2) floods the terminal with the following error:

`AL lib: (EE) ALCplaybackAlsa_mixerNoMMapProc: available update failed: Broken pipe`

Should we try with a shared version of OpenAL instead of the current static one?

**Comment by illwieckz** [comment]
This bug was fixed in last test packages built and shared by @maek. Perhaps this issue can be closed?

It was a build issue.

**Comment by maek** [comment]
Fixed in #32

**Comment by maek** [comment]
Fixed in #32
