### ISSUE TITLE
OS X build

### ISSUE THREAD

**Issue by maek** [unrealarena/unrealarena#6]
Make the game build and run also on Mac OS X.

**Comment by Kangz** [comment]
Daemon and Unvanquished build and run fine on OSX, what is the problem you have?

**Comment by maek** [comment]
Unfortunately we haven't any collaborator that has a Mac, so we need to ask to Travis CI if they allow us to build for OS X and then write a recipe for it.

**Comment by Kangz** [comment]
That makes sense, the engine itself shouldn't have trouble compiling on OSX as we make sure it works for Unvanquished. As for the gamelogic we never had any OSX-specific problem. But it is safer to wait to have a collaborator with a Mac yes. Thanks for the reply!
